application: stone-bindery-774
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers:
- url: /(.*\..*)
  static_files: \1
  upload: (.*\..*)

# site root
- url: /
  static_files: index.html
  upload: index.html
  expiration: "15m"
